name: Sync PHP Files
on:
  push:
    branches:
      - dev
    paths:
      - 'apps/php/src/apt_install.sh'
      - 'apps/php/src/cmd.sh'
      - 'apps/php/src/extensions.ini'
      - 'apps/php/src/php_extra.ini'
      - 'apps/php/src/php_install.sh'
jobs:
  sync-php-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Sync files to apps/phpfpmapache/src
      run: |
        root_dir=$(pwd)
        source_files_dir="$root_dir/apps/php/src"
        destination_dir="$root_dir/apps/phpfpmapache/src"
        changed_files=$(echo ${{ github.event.changed_files }} | tr ',' '\n')
        echo "get changed files list"
        file_list="apt_install.sh,cmd.sh,extensions.ini,php_extra.ini,php_install.sh"
        for file in $(echo $file_list | tr ',' '\n'); do
          if echo "$changed_files" | grep -q "$file"; then
            cp -f "$source_files_dir/$file" "$destination_dir"
            cd $destination_dir
            git add.
            git commit -m "Sync changes from apps/php/src/$file to apps/phpfpmapache/src" || true
            git push origin dev
            cd -
            echo "success"
          fi
        done

    - name: Sync files to apps/phpfpmnginx/src
      run: |
        root_dir=$(pwd)
        source_files_dir="$root_dir/apps/php/src"
        destination_dir="$root_dir/apps/phpfpmnginx/src"
        changed_files=$(echo ${{ github.event.changed_files }} | tr ',' '\n')
        echo "get changed files list"
        file_list="apt_install.sh,cmd.sh,extensions.ini,php_extra.ini,php_install.sh"
        for file in $(echo $file_list | tr ',' '\n'); do
          if echo "$changed_files" | grep -q "$file"; then
            cp -f "$source_files_dir/$file" "$destination_dir"
            cd $destination_dir
            git add.
            git commit -m "Sync changes from apps/php/src/$file to apps/phpfpmnginx/src" || true
            git push origin dev
            cd -
            echo "success"
          fi
        done